# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all the tests"
  lane :test do
    scan(device: "iPhone 7 (11.2)")
  end

  #desc "Download and refresh profiles"
  #lane :match do
  #  match(type: "development", app_identifier: "com.pilasvacias.test", force_for_new_devices: true)
  #  match(type: "appstore", app_identifier: "com.pilasvacias.test")
  #end

  desc "Upload a beta"
  lane :beta do
  	match(type: "appstore", readonly: true)
    
    increment_build_number(build_number: number_of_commits)
    
    #build_app
    #build_app(scheme: "travisTest")
    gym(
      configuration: "Release",
      sdk: "iphoneos11.2",
      clean: true,
      include_bitcode: true,
      include_symbols: true,
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
