# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all the tests"
  lane :test do
    scan(device: "iPhone 7 (11.2)")
  end

  #desc "Download and refresh profiles"
  #lane :match do
  #  match(type: "development", app_identifier: "com.pilasvacias.test", force_for_new_devices: true)
  #  match(type: "appstore", app_identifier: "com.pilasvacias.test")
  #end

  desc "Upload a beta"
  lane :beta do
  	match(type: "appstore", readonly: true)
    increment_build_number(build_number: number_of_commits)
  	build_app(scheme: "test")
  	upload_to_testflight
  end
end
